name = "OceanDynamicalModes"
uuid = "aa8f1f02-956a-4b02-bbda-bd8f5d8ddbac"
authors = ["Anthony Meza"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshArrays = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
MeshArrays = "0.3.17"
PyPlot = "2.11.5"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
