name = "OceanDynamicalModes"
uuid = "aa8f1f02-956a-4b02-bbda-bd8f5d8ddbac"
authors = ["Anthony Meza"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
